/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemRouteImport } from './routes/system'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs.$runId.index'
import { Route as RunsRunIdEvaluationRouteImport } from './routes/runs.$runId.evaluation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdEvaluationRoute = RunsRunIdEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => RunsRunIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/evaluation': typeof RunsRunIdEvaluationRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/runs/$runId/evaluation': typeof RunsRunIdEvaluationRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/evaluation': typeof RunsRunIdEvaluationRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system'
    | '/runs/$runId'
    | '/runs/$runId/evaluation'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/system' | '/runs/$runId/evaluation' | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/system'
    | '/runs/$runId'
    | '/runs/$runId/evaluation'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemRoute: typeof SystemRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/evaluation': {
      id: '/runs/$runId/evaluation'
      path: '/evaluation'
      fullPath: '/runs/$runId/evaluation'
      preLoaderRoute: typeof RunsRunIdEvaluationRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
  }
}

interface RunsRunIdRouteChildren {
  RunsRunIdEvaluationRoute: typeof RunsRunIdEvaluationRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdEvaluationRoute: RunsRunIdEvaluationRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemRoute: SystemRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
